use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use serde_with::serde_as;

use crate::schema::JsonSchema;
use crate::telemetry::{
    EmitDefaultOnError, EmitMapSkipError, EmitVecSkipError, schema_field_labels,
};

schema_field_labels! {
    ServiceCatalogItems         => "ServiceCatalog.items",
    ServiceInfoDescription      => "ServiceInfo.description",
    ServiceInfoHidden           => "ServiceInfo.hidden",
    ServiceInfoAlias            => "ServiceInfo.alias",
    ServiceSchemaId             => "ServiceSchema.id",
    ServiceSchemaBaseUrl        => "ServiceSchema.base_url",
    ServiceSchemaDescription    => "ServiceSchema.description",
    ServiceSchemaSkills         => "ServiceSchema.skills",
    ServiceSchemaRemoteDoc      => "ServiceSchema.remote_doc",
    ServiceSchemaSchemas        => "ServiceSchema.schemas",
    ServiceResourceId           => "ServiceResource.id",
    ServiceResourceHidden       => "ServiceResource.hidden",
    ServiceResourceRemoteDoc    => "ServiceResource.remote_doc",
    ServiceResourceMethods      => "ServiceResource.methods",
    ServiceResourceResources    => "ServiceResource.resources",
    MethodSchemaId              => "MethodSchema.id",
    MethodSchemaBaseUrl         => "MethodSchema.base_url",
    MethodSchemaPathAlias       => "MethodSchema.path_alias",
    MethodSchemaDescription     => "MethodSchema.description",
    MethodSchemaSkills          => "MethodSchema.skills",
    MethodSchemaHidden          => "MethodSchema.hidden",
    MethodSchemaRemoteDoc       => "MethodSchema.remote_doc",
    MethodSchemaRangeSize       => "MethodSchema.range_size",
    MethodSchemaRequest         => "MethodSchema.request",
    MethodSchemaResponse        => "MethodSchema.response",
    SchemaRefRef                => "SchemaRef.$ref",
}

/// Catalog of all available services returned by the discovery endpoint.
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ServiceCatalog {
    /// List of service entries (malformed entries are silently skipped).
    #[serde_as(as = "EmitVecSkipError<ServiceCatalogItems>")]
    pub items: Vec<ServiceInfo>,
}

/// Summary information for a single service.
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ServiceInfo {
    /// Unique service identifier (e.g. `"hr"`, `"doc"`).
    pub name: String,

    /// Human-readable description (empty string if not provided by server).
    #[serde_as(as = "EmitDefaultOnError<ServiceInfoDescription>")]
    #[serde(default)]
    pub description: String,

    /// When `true`, the service subcommand is hidden from help output.
    #[serde_as(as = "EmitDefaultOnError<ServiceInfoHidden>")]
    #[serde(default, skip_serializing_if = "is_false")]
    pub hidden: bool,

    /// Alternative names/aliases for this service (e.g. `["contact", "c"]`).
    #[serde_as(as = "EmitDefaultOnError<ServiceInfoAlias>")]
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub alias: Vec<String>,
}

/// Full schema of a service, including methods, resources, and type definitions.
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct ServiceSchema {
    /// Backend-declared stable identifier for this service, used as the `id`
    /// in remote doc requests when `remote_doc` is in effect.
    #[serde_as(as = "EmitDefaultOnError<ServiceSchemaId>")]
    #[serde(default)]
    pub id: Option<String>,

    /// Base URL for the service API endpoints.
    #[serde_as(as = "EmitDefaultOnError<ServiceSchemaBaseUrl>")]
    #[serde(default)]
    pub base_url: Option<String>,

    /// Service description (if any).
    #[serde_as(as = "EmitDefaultOnError<ServiceSchemaDescription>")]
    #[serde(default)]
    pub description: Option<String>,

    /// List of skills provided by the backend for this service,
    /// used for user guidance when a method is not found.
    #[serde_as(as = "EmitDefaultOnError<ServiceSchemaSkills>")]
    #[serde(default)]
    pub skills: Vec<String>,

    /// When `true`, documentation flags (`--doc` / `--help` / `--schema`)
    /// for this service are generated by the remote doc endpoint instead of
    /// being rendered locally. Overridable per resource / method.
    #[serde_as(as = "EmitDefaultOnError<ServiceSchemaRemoteDoc>")]
    #[serde(default)]
    pub remote_doc: Option<bool>,

    /// Named JSON Schema definitions referenced by `$ref` in methods.
    #[serde_as(as = "EmitDefaultOnError<ServiceSchemaSchemas>")]
    #[serde(default)]
    pub schemas: IndexMap<String, JsonSchema>,

    /// Root resource tree (methods + nested resources).
    #[serde(flatten)]
    pub resource_tree: ServiceResource,
}

/// A node in the service resource tree, containing methods and child resources.
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct ServiceResource {
    /// Backend-declared stable identifier for this resource, used as the
    /// `id` in remote doc requests when `remote_doc` is in effect.
    #[serde_as(as = "EmitDefaultOnError<ServiceResourceId>")]
    #[serde(default)]
    pub id: Option<String>,

    /// Methods directly available on this resource.
    #[serde_as(
        as = "EmitDefaultOnError<ServiceResourceMethods, EmitMapSkipError<ServiceResourceMethods, _, _>>"
    )]
    #[serde(default)]
    pub methods: IndexMap<String, MethodSchema>,

    /// Child resources (sub-namespaces).
    #[serde_as(
        as = "EmitDefaultOnError<ServiceResourceResources, EmitMapSkipError<ServiceResourceResources, _, _>>"
    )]
    #[serde(default)]
    pub resources: IndexMap<String, ServiceResource>,

    /// When `true`, the resource subcommand is hidden from help output.
    #[serde_as(as = "EmitDefaultOnError<ServiceResourceHidden>")]
    #[serde(default, skip_serializing_if = "is_false")]
    pub hidden: bool,

    /// When `true`, documentation flags (`--doc` / `--help` / `--schema`)
    /// for this resource subtree are generated by the remote doc endpoint
    /// instead of being rendered locally. Overrides the service-level value.
    #[serde_as(as = "EmitDefaultOnError<ServiceResourceRemoteDoc>")]
    #[serde(default)]
    pub remote_doc: Option<bool>,
}

/// Schema definition of a single API method.
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct MethodSchema {
    /// Backend-declared stable identifier for this method, used as the `id`
    /// in remote doc requests when `remote_doc` is in effect.
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaId>")]
    #[serde(default)]
    pub id: Option<String>,

    /// Base URL for the method API endpoints.
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaBaseUrl>")]
    #[serde(default)]
    pub base_url: Option<String>,

    /// HTTP method (`GET`, `POST`, etc.).
    pub http_method: String,

    /// URL path relative to the service `base_url` (e.g. `/user/get`).
    pub path: String,

    /// Path alias (if any).
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaPathAlias>")]
    #[serde(default)]
    pub path_alias: Option<Vec<String>>,

    /// Human-readable description (if any).
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaDescription>")]
    #[serde(default)]
    pub description: Option<String>,

    /// List of skills provided by the backend for this method,
    /// used for user guidance when a method call fails.
    /// Overrides [`ServiceSchema::skills`] when non-empty.
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaSkills>")]
    #[serde(default)]
    pub skills: Vec<String>,

    /// Reference to the request body schema (if any).
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaRequest>")]
    #[serde(default)]
    pub request: Option<SchemaRef>,

    /// Reference to the response body schema (if any).
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaResponse>")]
    #[serde(default)]
    pub response: Option<SchemaRef>,

    /// When `true`, the method subcommand is hidden from help output.
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaHidden>")]
    #[serde(default, skip_serializing_if = "is_false")]
    pub hidden: bool,

    /// When `true`, documentation flags (`--doc` / `--help` / `--schema`)
    /// for this method are generated by the remote doc endpoint instead of
    /// being rendered locally. Overrides the service / resource-level value.
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaRemoteDoc>")]
    #[serde(default)]
    pub remote_doc: Option<bool>,

    /// Chunk size (bytes) for HTTP Range download, from `range_size`.
    ///
    /// When present (`> 0`), the method's binary download is fetched in
    /// fixed-size Range segments; absent → single-shot download (unchanged
    /// behavior). Malformed values (`0`, negative, wrong type) silently
    /// fall back to `None` via `DefaultOnError`.
    #[serde_as(as = "EmitDefaultOnError<MethodSchemaRangeSize>")]
    #[serde(default)]
    pub range_size: Option<u64>,
}

/// A `{ "$ref": "TypeName" }` reference to a named schema definition.
#[serde_as]
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct SchemaRef {
    /// The referenced schema name (e.g. `"GetUserReq"`).
    #[serde_as(as = "EmitDefaultOnError<SchemaRefRef>")]
    #[serde(rename = "$ref", default)]
    pub schema_ref: Option<String>,
}

/// serde `skip_serializing_if` helper: skip `false` values.
fn is_false(b: &bool) -> bool {
    !*b
}

/// Find a service in `items` by name: an exact `name` match wins over an
/// `alias` match; returns `None` when neither hits.
pub(crate) fn find_service_by_name<'a>(
    items: &'a [ServiceInfo],
    name: &str,
) -> Option<&'a ServiceInfo> {
    items.iter().find(|info| info.name == name).or_else(|| {
        items
            .iter()
            .find(|info| info.name == name || info.alias.iter().any(|a| a == name))
    })
}

#[cfg(test)]
mod tests {
    //! ## 模块摘要：registry::types（服务注册表数据结构）
    //!
    //! ### 关键接口
    //! - [ServiceCatalog] — 服务目录（顶层 items 数组）
    //! - [ServiceInfo] — 单个服务元信息（name/description）
    //! - [find_service_by_name] — 按 name/alias 在列表中解析服务（精确 name 优先）
    //! - [ServiceSchema] — 服务 Schema（base_url/methods/resources）
    //! - [MethodSchema] — 方法 Schema（path/http_method/request/response）
    //! - [EmitDefaultOnError] — 容错反序列化 + 遥测上报：字段类型错误时回退默认值并 emit
    //! - [EmitVecSkipError] — 容错反序列化 + 遥测上报：跳过数组中的错误元素并 emit
    //! - [EmitMapSkipError] — 容错反序列化 + 遥测上报：跳过 map 中的错误条目并 emit
    //!
    //! ### 关键分支与异常路径
    //! - 缺少必填字段 → 反序列化失败
    //! - 缺少可选字段 → 使用默认值（None/空）
    //! - 数组元素解析失败 → 被 EmitVecSkipError 跳过并上报 schema_parse_error
    //! - Map 条目解析失败 → 被 EmitMapSkipError 跳过并上报 schema_parse_error
    //! - 字段类型错误 → EmitDefaultOnError 回退默认值并上报 schema_parse_error
    //! - 嵌套资源树 → 按层级正确解析
    //! - alias 解析：name 与 alias 冲突 → 精确 name 优先；均未命中 → None
    //!
    //! ### 上下游交互
    //! - 上游：[ServiceRegistry] 反序列化 discovery 响应到这些类型
    //! - 下游：被 [ServiceHandle]、[MethodHandle] 使用
    //! - 遥测：Emit* 适配器通过 [telemetry::emit] 上报到 CaptureScope

    use std::sync::{Arc, Mutex};

    use tracing_subscriber::prelude::*;

    use super::*;
    use crate::telemetry::contract::schema_parse_error as ctr;
    use crate::telemetry::{CaptureScope, ClientEvent, EventExt, TelemetryLayer};

    /// 测试 helper：注册共享 emit callsite 并重建 interest 缓存（机理见
    /// crate::telemetry::event_capture 测试模块的同名 helper）。
    /// 使用时机：`set_default` 之后、`CaptureScope::new()` 之前；
    /// 热身事件不进入断言。
    fn warm_up_emit_callsite() {
        crate::telemetry::emit("test_warmup", &serde_json::json!({}));
        tracing::callsite::rebuild_interest_cache();
    }

    // ── alias 解析 ──

    /// 构造仅含 name/alias 的 ServiceInfo 测试夹具
    fn service_info(name: &str, alias: &[&str]) -> ServiceInfo {
        ServiceInfo {
            name: name.to_string(),
            description: String::new(),
            hidden: false,
            alias: alias.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// P0：[find_service_by_name] 按精确 name 命中服务
    /// 条件：items 含 name="hr" 的服务，以 "hr" 查询
    /// 断言：返回 Some 且 name == "hr"
    #[test]
    fn find_service_by_name_exact_match() {
        let items = vec![service_info("hr", &[]), service_info("doc", &[])];
        assert_eq!(
            find_service_by_name(&items, "hr").map(|i| i.name.as_str()),
            Some("hr")
        );
    }

    /// P0：[find_service_by_name] 按 alias 命中服务并解析出规范 name
    /// 条件：items 含 name="hr"、alias=["contact"] 的服务，以 "contact" 查询
    /// 断言：返回 Some 且 name == "hr"
    #[test]
    fn find_service_by_name_alias_match() {
        let items = vec![service_info("hr", &["contact"])];
        assert_eq!(
            find_service_by_name(&items, "contact").map(|i| i.name.as_str()),
            Some("hr")
        );
    }

    /// P1：[find_service_by_name] name 与 alias 冲突时精确 name 优先
    /// 条件：服务 A（name="a"，alias=["b"]）位于服务 B（name="b"）之前，以 "b" 查询
    /// 断言：返回 name == "b" 的服务 B，而非 alias 命中的服务 A
    #[test]
    fn find_service_by_name_prefers_exact_name_over_alias() {
        let items = vec![service_info("a", &["b"]), service_info("b", &[])];
        assert_eq!(
            find_service_by_name(&items, "b").map(|i| i.name.as_str()),
            Some("b")
        );
    }

    /// P1：[find_service_by_name] name 与 alias 均未命中时返回 None
    /// 条件：items 中不存在 name 或 alias 为 "unknown" 的服务
    /// 断言：返回 None
    #[test]
    fn find_service_by_name_miss_returns_none() {
        let items = vec![service_info("hr", &["contact"])];
        assert!(find_service_by_name(&items, "unknown").is_none());
    }

    // ── 反序列化测试 ──

    /// P0：[ServiceCatalog] 的基本反序列化
    /// 条件：JSON 包含 items 数组，每个元素有 name 和 description
    /// 断言：正确解析出 1 个服务条目，name 和 description 匹配
    #[test]
    fn deserialize_service_catalog() {
        let json = r#"{ "items": [{ "name": "user", "description": "用户管理" }] }"#;
        let catalog: ServiceCatalog = serde_json::from_str(json).unwrap();
        assert_eq!(catalog.items.len(), 1);
        assert_eq!(catalog.items[0].name, "user");
        assert_eq!(catalog.items[0].description, "用户管理");
    }

    /// P1：[ServiceCatalog] 空 items 数组的反序列化
    /// 条件：JSON 中 items 为空数组
    /// 断言：解析后 catalog.items 为空
    #[test]
    fn deserialize_service_catalog_empty_items() {
        let json = r#"{ "items": [] }"#;
        let catalog: ServiceCatalog = serde_json::from_str(json).unwrap();
        assert!(catalog.items.is_empty());
    }

    /// P1：[ServiceInfo] 缺少 description 字段时回退为默认空字符串
    /// 条件：JSON 仅包含 name 字段，无 description
    /// 断言：description 为空字符串 ""
    #[test]
    fn deserialize_service_item_missing_description() {
        let json = r#"{ "name": "dept" }"#;
        let info: ServiceInfo = serde_json::from_str(json).unwrap();
        assert_eq!(info.name, "dept");
        assert_eq!(info.description, "");
    }

    /// P0：[ServiceSchema] 完整 ServiceSchema 的反序列化
    /// 条件：JSON 包含 description、base_url、schemas、methods、resources
    /// 断言：各字段均正确解析，包括嵌套的 schemas 和 methods
    #[test]
    fn deserialize_service_description() {
        let json = r#"{
            "description": "部门服务",
            "base_url": "https://example.com",
            "schemas": {
                "Dept": { "type": "object" }
            },
            "methods": {
                "list": {
                    "path": "/dept/list",
                    "http_method": "GET",
                    "description": "获取部门列表"
                }
            },
            "resources": {}
        }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert_eq!(schema.description, Some("部门服务".to_string()));
        assert_eq!(schema.base_url.as_deref(), Some("https://example.com"));
        assert!(schema.schemas.contains_key("Dept"));
        assert!(schema.resource_tree.methods.contains_key("list"));
    }

    /// P0：[ServiceSchema] 最小化 ServiceSchema（仅 base_url）的反序列化
    /// 条件：JSON 仅包含 base_url 字段
    /// 断言：base_url 正确解析，其余可选字段均为默认值（空/None）
    #[test]
    fn deserialize_service_description_minimal() {
        let json = r#"{ "base_url": "https://example.com" }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert_eq!(schema.base_url.as_deref(), Some("https://example.com"));
        assert!(schema.description.is_none());
        assert!(schema.schemas.is_empty());
        assert!(schema.resource_tree.methods.is_empty());
        assert!(schema.resource_tree.resources.is_empty());
    }

    /// P0：[MethodSchema] 含 request/response $ref 的反序列化
    /// 条件：JSON 包含 path、http_method、description、request、response
    /// 断言：各字段及 $ref 引用名称均正确解析
    #[test]
    fn deserialize_service_method() {
        let json = r#"{
            "path": "/user/get",
            "http_method": "POST",
            "description": "获取用户",
            "request": { "$ref": "GetUserReq" },
            "response": { "$ref": "GetUserResp" }
        }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert_eq!(method.path, "/user/get");
        assert_eq!(method.http_method, "POST");
        assert_eq!(
            method.request.as_ref().unwrap().schema_ref,
            Some("GetUserReq".to_string())
        );
        assert_eq!(
            method.response.as_ref().unwrap().schema_ref,
            Some("GetUserResp".to_string())
        );
    }

    /// P1：[MethodSchema] 缺少可选字段时的最小化反序列化
    /// 条件：JSON 仅包含 path 和 http_method，无 description/request/response
    /// 断言：可选字段均为 None
    #[test]
    fn deserialize_service_method_no_schema_refs() {
        let json = r#"{ "path": "/ping", "http_method": "GET" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.description.is_none());
        assert!(method.request.is_none());
        assert!(method.response.is_none());
    }

    /// P0：[ServiceSchema] 嵌套资源树（department → member）的反序列化
    /// 条件：JSON 包含两层嵌套 resources 和各自 methods
    /// 断言：可按层级访问到 department.create 和 member.list
    #[test]
    fn deserialize_nested_resources() {
        let json = r#"{
            "base_url": "https://example.com",
            "resources": {
                "department": {
                    "methods": {
                        "create": {
                            "path": "/dept/create",
                            "http_method": "POST"
                        }
                    },
                    "resources": {
                        "member": {
                            "methods": {
                                "list": {
                                    "path": "/dept/member/list",
                                    "http_method": "GET"
                                }
                            }
                        }
                    }
                }
            }
        }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        let dept = &schema.resource_tree.resources["department"];
        assert!(dept.methods.contains_key("create"));
        let member = &dept.resources["member"];
        assert!(member.methods.contains_key("list"));
        assert_eq!(member.methods["list"].path, "/dept/member/list");
    }

    // ── DefaultOnError / VecSkipError / MapSkipError 容错测试 ──

    /// P1：[VecSkipError] 跳过格式错误的数组元素
    /// 条件：items 中第 2 个元素缺少必填字段 name
    /// 断言：仅解析出 2 个有效条目（user 和 dept），坏元素被静默跳过
    #[test]
    fn vec_skip_error_skips_bad_items() {
        // 第 2 个元素缺少必填字段 name，应被跳过
        let json = r#"{ "items": [
            { "name": "user", "description": "用户" },
            { "bad_field": true },
            { "name": "dept" }
        ] }"#;
        let catalog: ServiceCatalog = serde_json::from_str(json).unwrap();
        assert_eq!(catalog.items.len(), 2);
        assert_eq!(catalog.items[0].name, "user");
        assert_eq!(catalog.items[1].name, "dept");
    }

    /// P1：[VecSkipError] 在全部元素均无效时返回空数组
    /// 条件：items 数组中所有元素都不是合法对象
    /// 断言：解析后 catalog.items 为空
    #[test]
    fn vec_skip_error_skips_all_bad_items() {
        let json = r#"{ "items": [
            { "no_name": 1 },
            123,
            null
        ] }"#;
        let catalog: ServiceCatalog = serde_json::from_str(json).unwrap();
        assert!(catalog.items.is_empty());
    }

    /// ServiceInfo description 为 null 时回退为默认空字符串
    /// 条件：JSON 中 description 显式设为 null
    /// 断言：description 为 ""
    #[test]
    fn service_item_description_null_falls_back_to_default() {
        let json = r#"{ "name": "svc", "description": null }"#;
        let info: ServiceInfo = serde_json::from_str(json).unwrap();
        assert_eq!(info.description, "");
    }

    /// ServiceInfo description 类型错误时回退为默认值
    /// 条件：JSON 中 description 为数字 42
    /// 断言：description 回退为 ""
    #[test]
    fn service_item_description_wrong_type_falls_back_to_default() {
        let json = r#"{ "name": "svc", "description": 42 }"#;
        let info: ServiceInfo = serde_json::from_str(json).unwrap();
        assert_eq!(info.description, "");
    }

    /// ServiceSchema description 字段类型错误时回退为 None
    /// 条件：JSON 中 description 为数字 999
    /// 断言：schema.description 为 None
    #[test]
    fn service_description_description_wrong_type_falls_back() {
        let json = r#"{ "base_url": "https://x.com", "description": 999 }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert!(schema.description.is_none());
    }

    /// ServiceSchema schemas 字段类型错误时回退为空 map
    /// 条件：JSON 中 schemas 为字符串 "bad"
    /// 断言：schema.schemas 为空
    #[test]
    fn service_description_schemas_wrong_type_falls_back() {
        let json = r#"{ "base_url": "https://x.com", "schemas": "bad" }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert!(schema.schemas.is_empty());
    }

    /// methods 字段为非对象类型时 DefaultOnError 回退为空 map
    /// 条件：JSON 中 methods 为字符串 "garbage"
    /// 断言：resource_tree.methods 为空
    #[test]
    fn methods_wrong_type_falls_back_to_empty() {
        // methods 字段整个给非对象值，DefaultOnError 保护回退为空 map
        let json = r#"{ "base_url": "https://x.com", "methods": "garbage" }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert!(schema.resource_tree.methods.is_empty());
    }

    /// resources 字段为非对象类型时回退为空 map
    /// 条件：JSON 中 resources 为数字 123
    /// 断言：resource_tree.resources 为空
    #[test]
    fn resources_wrong_type_falls_back_to_empty() {
        let json = r#"{ "base_url": "https://x.com", "resources": 123 }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert!(schema.resource_tree.resources.is_empty());
    }

    /// MapSkipError 跳过格式错误的 method 条目
    /// 条件：methods 中 "broken" 缺少必填 path/http_method
    /// 断言：仅保留有效的 "list" 条目
    #[test]
    fn map_skip_error_skips_bad_method_entries() {
        // "broken" 缺少必填 path/http_method，MapSkipError 应跳过它
        let json = r#"{
            "base_url": "https://x.com",
            "methods": {
                "list": { "path": "/list", "http_method": "GET" },
                "broken": { "not_valid": true }
            }
        }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert_eq!(schema.resource_tree.methods.len(), 1);
        assert!(schema.resource_tree.methods.contains_key("list"));
    }

    /// MapSkipError 跳过格式错误的 resource 条目
    /// 条件：resources 中 "bad_res" 为字符串而非对象
    /// 断言：仅保留有效的 "good" 资源
    #[test]
    fn map_skip_error_skips_bad_resource_entries() {
        // "bad_res" 的 methods 里有格式错误的条目
        let json = r#"{
            "base_url": "https://x.com",
            "resources": {
                "good": {
                    "methods": {
                        "get": { "path": "/get", "http_method": "GET" }
                    }
                },
                "bad_res": "not_an_object"
            }
        }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert_eq!(schema.resource_tree.resources.len(), 1);
        assert!(schema.resource_tree.resources.contains_key("good"));
    }

    /// MethodSchema description 类型错误时回退为 None
    /// 条件：JSON 中 description 为数组 [1,2]
    /// 断言：method.description 为 None
    #[test]
    fn service_method_description_wrong_type_falls_back() {
        let json = r#"{ "path": "/x", "http_method": "GET", "description": [1,2] }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.description.is_none());
    }

    /// MethodSchema request 类型错误时回退为 None
    /// 条件：JSON 中 request 为字符串 "bad"
    /// 断言：method.request 为 None
    #[test]
    fn service_method_request_wrong_type_falls_back() {
        let json = r#"{ "path": "/x", "http_method": "GET", "request": "bad" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.request.is_none());
    }

    /// MethodSchema response 类型错误时回退为 None
    /// 条件：JSON 中 response 为数字 42
    /// 断言：method.response 为 None
    #[test]
    fn service_method_response_wrong_type_falls_back() {
        let json = r#"{ "path": "/x", "http_method": "GET", "response": 42 }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.response.is_none());
    }

    // ── skills ──

    /// P1：[MethodSchema] 反序列化 method 级 skills 列表
    /// 条件：JSON 含 skills: ["a", "b"]
    /// 断言：method.skills == ["a", "b"]
    #[test]
    fn deserialize_method_skills() {
        let json = r#"{ "path": "/x", "http_method": "GET", "skills": ["a", "b"] }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert_eq!(method.skills, vec!["a".to_string(), "b".to_string()]);
    }

    /// P1：[MethodSchema] 缺省 skills 时回退为空列表
    /// 条件：JSON 不含 skills
    /// 断言：method.skills 为空
    #[test]
    fn deserialize_method_skills_absent() {
        let json = r#"{ "path": "/x", "http_method": "GET" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.skills.is_empty());
    }

    /// P1：[MethodSchema] skills 类型错误时回退为空列表并上报正确 field 标签
    /// 条件：JSON 中 skills 为字符串 "bad"
    /// 断言：method.skills 为空，且收到 field="MethodSchema.skills" 遥测事件
    #[test]
    fn deserialize_method_skills_wrong_type_falls_back() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let method: MethodSchema =
            serde_json::from_str(r#"{ "path": "/x", "http_method": "GET", "skills": "bad" }"#)
                .unwrap();
        drop(_enter);

        assert!(method.skills.is_empty());
        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("MethodSchema.skills")
        );
    }

    // ── range_size ──

    /// P0：[MethodSchema] 反序列化 range_size 为正整数
    /// 条件：JSON 含 range_size: 4194304
    /// 断言：method.range_size == Some(4194304)
    #[test]
    fn deserialize_range_size_positive() {
        let json = r#"{ "path": "/file/download", "http_method": "POST", "range_size": 4194304 }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert_eq!(method.range_size, Some(4194304));
    }

    /// P0：[MethodSchema] 缺省 range_size 时 range_size 为 None
    /// 条件：JSON 不含 range_size
    /// 断言：method.range_size == None
    #[test]
    fn deserialize_range_size_absent() {
        let json = r#"{ "path": "/x", "http_method": "GET" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.range_size.is_none());
    }

    /// P1：[MethodSchema] range_size 为 0 时反序列化为 Some(0)（合法 u64）
    /// 条件：JSON 含 range_size: 0
    /// 断言：method.range_size == Some(0)（MethodHandle::range_size 会过滤掉 0）
    #[test]
    fn deserialize_range_size_zero_is_some_zero() {
        let json = r#"{ "path": "/x", "http_method": "GET", "range_size": 0 }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert_eq!(method.range_size, Some(0));
    }

    /// P1：[MethodSchema] range_size 类型错误时回退为 None
    /// 条件：JSON 中 range_size 为字符串 "big"
    /// 断言：method.range_size == None（DefaultOnError 容错，不 panic）
    #[test]
    fn deserialize_range_size_wrong_type_falls_back() {
        let json = r#"{ "path": "/x", "http_method": "GET", "range_size": "big" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.range_size.is_none());
    }

    // ── remote_doc / id ──

    /// P0：[MethodSchema] 反序列化 remote_doc 为 true
    /// 条件：JSON 含 remote_doc: true
    /// 断言：method.remote_doc == Some(true)
    #[test]
    fn deserialize_method_remote_doc_true() {
        let json = r#"{ "path": "/x", "http_method": "GET", "remote_doc": true }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert_eq!(method.remote_doc, Some(true));
    }

    /// P1：[MethodSchema] 缺省 remote_doc 时为 None
    /// 条件：JSON 不含 remote_doc
    /// 断言：method.remote_doc == None
    #[test]
    fn deserialize_method_remote_doc_absent() {
        let json = r#"{ "path": "/x", "http_method": "GET" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.remote_doc.is_none());
    }

    /// P1：[MethodSchema] remote_doc 类型错误时回退为 None
    /// 条件：JSON 中 remote_doc 为字符串 "yes"
    /// 断言：method.remote_doc == None（DefaultOnError 容错，不 panic）
    #[test]
    fn deserialize_method_remote_doc_wrong_type_falls_back() {
        let json = r#"{ "path": "/x", "http_method": "GET", "remote_doc": "yes" }"#;
        let method: MethodSchema = serde_json::from_str(json).unwrap();
        assert!(method.remote_doc.is_none());
    }

    /// P0：[ServiceSchema] 反序列化 service 级 remote_doc
    /// 条件：JSON 含 remote_doc: true
    /// 断言：schema.remote_doc == Some(true)
    #[test]
    fn deserialize_service_remote_doc_true() {
        let json = r#"{ "base_url": "https://x.com", "remote_doc": true }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert_eq!(schema.remote_doc, Some(true));
    }

    /// P0：[ServiceResource] 反序列化 resource 级 remote_doc
    /// 条件：嵌套 resource 含 remote_doc: false
    /// 断言：子 resource 的 remote_doc == Some(false)，根 resource 为 None
    #[test]
    fn deserialize_resource_remote_doc() {
        let json = r#"{
            "base_url": "https://x.com",
            "remote_doc": true,
            "resources": {
                "department": { "remote_doc": false }
            }
        }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert!(schema.resource_tree.remote_doc.is_none());
        assert_eq!(
            schema.resource_tree.resources["department"].remote_doc,
            Some(false)
        );
    }

    /// P1：[ServiceSchema] remote_doc 类型错误时回退为 None 并上报正确 field 标签
    /// 条件：JSON 中 remote_doc 为数字 1
    /// 断言：schema.remote_doc == None，且收到 field="ServiceSchema.remote_doc" 遥测事件
    #[test]
    fn deserialize_service_remote_doc_wrong_type_falls_back() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let schema: ServiceSchema =
            serde_json::from_str(r#"{ "base_url": "https://x.com", "remote_doc": 1 }"#).unwrap();
        drop(_enter);

        assert!(schema.remote_doc.is_none());
        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceSchema.remote_doc")
        );
    }

    /// P0：三层 schema 均反序列化 id 字段
    /// 条件：service / resource / method 各声明 id
    /// 断言：三层 id 均为对应值
    #[test]
    fn deserialize_id_fields() {
        let schema: ServiceSchema = serde_json::from_str(
            r#"{
                "id": "svc-hr",
                "base_url": "https://x.com",
                "resources": {
                    "department": {
                        "id": "res-department",
                        "methods": {
                            "list": { "id": "m-list", "path": "/list", "http_method": "GET" }
                        }
                    }
                }
            }"#,
        )
        .unwrap();
        assert_eq!(schema.id.as_deref(), Some("svc-hr"));
        let dept = &schema.resource_tree.resources["department"];
        assert_eq!(dept.id.as_deref(), Some("res-department"));
        assert_eq!(dept.methods["list"].id.as_deref(), Some("m-list"));
    }

    /// P1：[MethodSchema] id 缺省时为 None，类型错误时回退 None
    /// 条件：JSON 不含 id；id 为数字 1
    /// 断言：method.id 均为 None
    #[test]
    fn deserialize_method_id_fallbacks() {
        let method: MethodSchema =
            serde_json::from_str(r#"{ "path": "/x", "http_method": "GET" }"#).unwrap();
        assert!(method.id.is_none());
        let method: MethodSchema =
            serde_json::from_str(r#"{ "path": "/x", "http_method": "GET", "id": 1 }"#).unwrap();
        assert!(method.id.is_none());
    }

    /// SchemaRef $ref 类型错误时回退为 None
    /// 条件：JSON 中 $ref 为数字 123
    /// 断言：sr.schema_ref 为 None
    #[test]
    fn schema_ref_wrong_type_falls_back() {
        let json = r#"{ "$ref": 123 }"#;
        let sr: SchemaRef = serde_json::from_str(json).unwrap();
        assert!(sr.schema_ref.is_none());
    }

    /// 多个字段同时类型错误时全部回退为默认值
    /// 条件：description/schemas/methods/resources 均为非法类型
    /// 断言：所有可选字段均回退到默认值（None 或空）
    #[test]
    fn multiple_bad_fields_all_fall_back() {
        let json = r#"{
            "base_url": "https://x.com",
            "description": [],
            "schemas": 0,
            "methods": false,
            "resources": null
        }"#;
        let schema: ServiceSchema = serde_json::from_str(json).unwrap();
        assert_eq!(schema.base_url.as_deref(), Some("https://x.com"));
        assert!(schema.description.is_none());
        assert!(schema.schemas.is_empty());
        assert!(schema.resource_tree.methods.is_empty());
        assert!(schema.resource_tree.resources.is_empty());
    }

    // ── EmitDefaultOnError 遥测发射测试 ──

    /// P0：[EmitDefaultOnError] 字段类型错误时发射 schema_parse_error 遥测事件
    /// 条件：ServiceSchema.description 为数字 999 导致类型错误回退
    /// 断言：CaptureScope 收到 kind="schema_parse_error"、field="ServiceSchema.description"
    #[test]
    fn emit_default_fallback_on_type_error() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();

        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();

        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema =
            serde_json::from_str(r#"{ "base_url": "https://x.com", "description": 999 }"#).unwrap();
        drop(_enter);

        let snaps: Vec<ClientEvent> = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceSchema.description")
        );
    }

    /// P1：[EmitDefaultOnError] schemas 字段类型错误时上报正确 field 标签
    /// 条件：ServiceSchema.schemas 为字符串 "bad"
    /// 断言：field="ServiceSchema.schemas"
    #[test]
    fn emit_default_fallback_schemas_wrong_type() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema =
            serde_json::from_str(r#"{ "base_url": "https://x.com", "schemas": "bad" }"#).unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceSchema.schemas")
        );
    }

    /// P1：[EmitDefaultOnError] MethodSchema.request 类型错误时上报正确 field 标签
    /// 条件：MethodSchema.request 为字符串 "bad"
    /// 断言：field="MethodSchema.request"
    #[test]
    fn emit_default_fallback_method_request_wrong_type() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _method: MethodSchema =
            serde_json::from_str(r#"{ "path": "/x", "http_method": "GET", "request": "bad" }"#)
                .unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("MethodSchema.request")
        );
    }

    /// P1：[EmitDefaultOnError] 合法 schema 不发射遥测事件（fast path）
    /// 条件：合法 JSON，所有字段类型正确
    /// 断言：CaptureScope 没有收到任何事件
    #[test]
    fn emit_default_fallback_no_event_on_valid_schema() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema =
            serde_json::from_str(r#"{ "base_url": "https://x.com" }"#).unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert!(snaps.is_empty());
    }

    /// P1：[EmitDefaultOnError] 多字段同时畸形时每个失败字段各发射一条事件
    /// 条件：description/schemas/methods/resources 均为非法类型
    /// 断言：收到 4 条 schema_parse_error，field 集合包含全部四个字段
    #[test]
    fn emit_default_fallback_multiple_bad_fields() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema = serde_json::from_str(
            r#"{
                "base_url": "https://x.com",
                "description": [],
                "schemas": 0,
                "methods": false,
                "resources": null
            }"#,
        )
        .unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 4);
        for ev in &snaps {
            assert_eq!(ev.kind, ctr::KIND);
        }
        let fields: Vec<&str> = snaps
            .iter()
            .map(|ev| ev.payload[ctr::FIELD_FIELD].as_str().unwrap())
            .collect();
        assert!(fields.contains(&"ServiceSchema.description"));
        assert!(fields.contains(&"ServiceSchema.schemas"));
        assert!(fields.contains(&"ServiceResource.methods"));
        assert!(fields.contains(&"ServiceResource.resources"));
    }

    /// P1：[EmitDefaultOnError] methods 整字段为非 map 时上报 schema_parse_error
    /// 条件：methods 字段为字符串 "garbage"（外层 DefaultOnError 捕获）
    /// 断言：field="ServiceResource.methods"
    #[test]
    fn emit_default_fallback_methods_not_a_map() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema =
            serde_json::from_str(r#"{ "base_url": "https://x.com", "methods": "garbage" }"#)
                .unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceResource.methods")
        );
    }

    // ── EmitVecSkipError 遥测发射测试 ──

    /// P0：[EmitVecSkipError] 数组含坏元素时发射 schema_parse_error 遥测事件
    /// 条件：items 中第 2 个元素缺少必填字段 name 且第 3 个元素为整数 123
    /// 断言：收到 1 条 kind="schema_parse_error"、field="ServiceCatalog.items"
    #[test]
    fn emit_skip_element_vec_skip_bad_items() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _catalog: ServiceCatalog = serde_json::from_str(
            r#"{ "items": [ { "name": "user", "description": "用户" }, { "bad_field": true }, 123 ] }"#,
        )
        .unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceCatalog.items")
        );
    }

    /// P1：[EmitVecSkipError] 全部元素无效时仍上报
    /// 条件：items 中所有元素都不是合法 ServiceInfo
    /// 断言：收到 1 条 schema_parse_error，field="ServiceCatalog.items"
    #[test]
    fn emit_skip_element_vec_all_bad() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _catalog: ServiceCatalog =
            serde_json::from_str(r#"{ "items": [ { "no_name": 1 }, 123, null ] }"#).unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceCatalog.items")
        );
    }

    // ── EmitMapSkipError 遥测发射测试 ──

    /// P0：[EmitMapSkipError] map 含坏条目时发射 schema_parse_error 遥测事件
    /// 条件：methods 中 "broken" 缺少必填 path/http_method
    /// 断言：收到 1 条 kind="schema_parse_error"、field="ServiceResource.methods"
    #[test]
    fn emit_skip_element_map_skip_bad_entry() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema = serde_json::from_str(
            r#"{
                "base_url": "https://x.com",
                "methods": {
                    "list": { "path": "/list", "http_method": "GET" },
                    "broken": { "not_valid": true }
                }
            }"#,
        )
        .unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert_eq!(snaps.len(), 1);
        assert_eq!(snaps[0].kind, ctr::KIND);
        assert_json_diff::assert_json_eq!(
            snaps[0].payload[ctr::FIELD_FIELD],
            serde_json::json!("ServiceResource.methods")
        );
    }

    /// P1：[EmitMapSkipError] map 全好时不发射事件
    /// 条件：methods 中所有条目均合法
    /// 断言：CaptureScope 没有收到任何事件
    #[test]
    fn emit_skip_element_map_no_event_on_all_valid() {
        let _guard = tracing::subscriber::set_default(
            tracing_subscriber::Registry::default().with(TelemetryLayer::new()),
        );
        warm_up_emit_callsite();
        let collected: Arc<Mutex<Vec<ClientEvent>>> = Arc::new(Mutex::new(Vec::new()));
        let c = collected.clone();
        let scope = CaptureScope::new();
        scope.on_event(move |ev: ClientEvent| {
            c.lock().unwrap().push(ev);
        });

        let _enter = scope.span().enter();
        let _schema: ServiceSchema = serde_json::from_str(
            r#"{
                "base_url": "https://x.com",
                "methods": {
                    "list": { "path": "/list", "http_method": "GET" }
                }
            }"#,
        )
        .unwrap();
        drop(_enter);

        let snaps = std::mem::take(&mut *collected.lock().unwrap());
        assert!(snaps.is_empty());
    }
}
